CREATE TABLE duos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nameTeam VARCHAR(100) DEFAULT NULL,
  numberTeam INT NOT NULL,
  playerOne VARCHAR(100) DEFAULT NULL,
  playerTwo VARCHAR(100) DEFAULT NULL,
  groupTeam VARCHAR(100) DEFAULT NULL,
  position INT NOT NULL,
  playDate VARCHAR(100) DEFAULT NULL,
  phase INT NOT NULL);